#!/usr/bin/env bash
# its a Bash script that will display the listening ports:
#     -  only shows the listening sockets
#     -  shows the PID and name of the program to the socket to wich it belongs
netstat -tupn
