#!/usr/bin/env bash
# This script configures the /etc/hosts file to resolve localhost
#and facebook.com to specific IPs.

# Backup the original /etc/hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Modify the /etc/hosts file
sudo sed -i '/127.0.0.1\s*localhost/d' /etc/hosts
sudo sed -i '/facebook.com/d' /etc/hosts

# This is adding new entries for facebook
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null

echo "Hosts file modified successfully."